export { default as Header } from './Header'
export { default as Hero } from './Hero'
export { default as Services } from './Services'
export { default as Stats } from './Stats'
export { default as Testimonials } from './Testimonials'
export { default as Footer } from './Footer'
